name: test

on:
  push:
  schedule:
    - cron:  '* 9 * * *'

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macos-11, windows-2022]
        deno: [1.16.0, 1.14.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Lint
        run: deno lint --config deno.json

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macos-11, windows-2022]
        deno: [1.16.0, 1.14.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Lint
        run: deno test --ignore=node_modules --config deno.json --import-map=import_map.json
