name: test

on:
  push:
  schedule:
    - cron:  '* 9 * * *'

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macos-latest, windows-latest]
        deno: [1.16.0, 1.14.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Lint
        run: |
          deno fmt -c deno.json
          deno lint -c deno.json

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macos-latest, windows-latest]
        deno: [1.16.0, 1.14.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Test
        run: deno test --ignore=node_modules,README.md,matcher/README.md -c deno.json --doc
